### ISSUE TITLE
Crash with 1.4

### ISSUE THREAD

**Issue by reoseah** [FabricCompatibilityLayers/Fabricated-Legacy-Forge#18]
I've cloned legacy fabric example, added mod remapping api and fabricated forge for 1.3.2, which worked, then bumped all versions to 1.4, and it crashes.

Here's my code: https://github.com/Reoseah/psychic-octo-memory/tree/018267110c3aad91ef38596d274841d35a67b008

Full crash log in attachment, error happens here:
```
[14:59:41] [main/ERROR] (FabricLoader/Mixin) Mixin apply for mod fabricated-forge failed fabricated-forge.forge.mixins.json:world.WorldMixin from mod fabricated-forge -> net.minecraft.world.World: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PROTECTED @Overwrite method tickWeather in fabricated-forge.forge.mixins.json:world.WorldMixin from mod fabricated-forge cannot reduce visibiliy of PUBLIC target method
 org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: PROTECTED @Overwrite method tickWeather in fabricated-forge.forge.mixins.json:world.WorldMixin from mod fabricated-forge cannot reduce visibiliy of PUBLIC target method
```
[crash.txt](https://github.com/arthurbambou/Fabricated-Legacy-Forge/files/10047153/crash.txt)

**Comment by reoseah** [comment]
Version 1.3.2 succesfully runs in IDE env, if it helps: https://github.com/Reoseah/psychic-octo-memory/commit/a554f001ab8871477ca3f78d949202c51bb6b5ea

**Comment by halotroop2288** [comment]
This doesn't look like a Fabricated Forge bug at all. You just need to change the visibility of your Mixin member after updating.

**Comment by reoseah** [comment]
Wdym? I have no mixins in my mod, and the failing one is from Fabricated Forge

**Comment by reoseah** [comment]
https://github.com/arthurbambou/Fabricated-Legacy-Forge/blob/c78e07d4a717e57262f488fe3806b057d552a3f0/src/main/java/fr/catcore/fabricatedforge/mixin/forgefml/world/WorldMixin.java#L948 here, found it, this `@Overwrite` method probably should be public

**Comment by thecatcore** [comment]
Yea it’s a dev only problem, I usually test this mod only in prod as that is where it is supposed to be used and some stuff doesn’t work the same way in dev.
