### ISSUE TITLE
support for versions 1 19 2 and 1 19 4

### ISSUE THREAD

**Issue by DefomCode** [FabricCompatibilityLayers/Fabricated-Legacy-Forge#25]
## Description:

will there be support for versions 1 19 2-1 19 4 ?

**Comment by halotroop2288** [comment]
No. This mod is for Legacy Fabric. Versions 1.3.2 - 1.13.2

That's why "Legacy" is in the name.

**Comment by DefomCode** [comment]
> No. This mod is for Legacy Fabric. Versions 1.3.2 - 1.13.2
> 
> That's why "Legacy" is in the name.

aww.. okay. It's just that there is no Legacy inscription on Modrinth

**Comment by thecatcore** [comment]
1.13+ support is not planned

**Comment by Sunconure11** [comment]
Didn't see this before writing my own question about this, @thecatcore, but do you know of anyone planning something similar, but for newer builds?

**Comment by halotroop2288** [comment]
> do you know of anyone planning something similar, but for newer builds?

Assuming you meant newer Minecraft releases:
https://github.com/KiltMC

Tell them we sent you. I'm curious to see if they know about us.

**Comment by Sunconure11** [comment]
I knew about one of their devs, but didn't realize Kilt went this far until he told me.

And yes, he knows of you. You guys were the inspiration for Kilt. But right now, BluSpring is the only dev working on Kilt.

**Comment by halotroop2288** [comment]
We would love to have them join us on Discord. Any dev of a compat layer gets a channel to manage as they please.
