### ISSUE TITLE
[1.3.2/1.4.7] [Mod Support] NotEnoughItems

### ISSUE THREAD

**Issue by ghost** [FabricCompatibilityLayers/Fabricated-Legacy-Forge#30]
Minecraft version: 1.3.2, 1.4.7

Fabricated-Forge version: 2.7.3 (1.3.2), 2.7.2 (1.4.7)

Fabric Loader version: 0.16.7

Java version: 1.8.0_422

Mod name: NotEnoughItems

Mod download link (needed for testing): https://chickenbones.net/Files/Old_Versions/

Description of the bug: Upon joining a world and opening the inventory, the game crashes

If crash, link to pastbin of the crash report: https://mclo.gs/Ta7y6QM

**Comment by thecatcore** [comment]
Trying putting CCC and REI in the coremods folder instead of simply mods.

**Comment by ghost** [comment]
That fixed the issue, thanks!
