### ISSUE TITLE
[1.4.7] [Mod Support] OptiFine/OptiFabric

### ISSUE THREAD

**Issue by ghost** [FabricCompatibilityLayers/Fabricated-Legacy-Forge#31]
Minecraft version: 1.4.7

Fabricated-Forge version: 2.7.2

Fabric Loader version: 0.16.7

Java version: 1.8.0_422

Mod name: OptiFine / Legacy OptiFabric

Mod download link (needed for testing): https://modrinth.com/mod/legacy-optifabric, https://optifine.net/adloadx?f=OptiFine_1.4.6_HD_U_D5.zip

Description of the bug: OptiFine + OptiFabric by itself works fine, same as FLF + Mod Remapping API. But those 4 together cause the game to hang on the Mojang screen and eventually crash.

If crash, link to pastbin of the crash report: https://mclo.gs/VRUv668

**Comment by thecatcore** [comment]
Fixed in 2.7.5. Use with Legacy OptiFabric 2.3.4+ when it is released.
