### ISSUE TITLE
Why 1.3?

### ISSUE THREAD

**Issue by Madis0** [FabricCompatibilityLayers/Fabricated-Legacy-Forge#8]
Of all possible versions, why port Minecraft Forge 1.3.2 specifically? Seems a bit arbitrary 😄
I'm aware that the codebase was simpler back then, but I recall the first big refactor only happening in 1.8, so why didn't you choose 1.7.10 for example?

**Comment by thecatcore** [comment]
Reasons:

1. It's the oldest Minecraft version that both Legacy Fabric and Forge support
2. It's old Forge so less patches to port.
3. It's old Forge so no dealing with LaunchWrapper so easier to make work.
4. It's close to Forge 1.2.5 that has really basic support in Fabric Loader.
5. I plan to go up in Minecraft/Forge versions over the time.

**Comment by Madis0** [comment]
Thanks!
